include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_return: error
    missing_required_param: error
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.model.dart"
    - "**/*.state.dart"
    - "**/*.repository.dart"
    - "**/*.form.dart"
    - "**/*.state_manager.dart"
    - "**/*.view.dart"
    - "**/*.config.dart"
    - "**/*.router.dart"
    - "**/*.dragonfly.dart"

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - directives_ordering
    - discarded_futures
    - omit_local_variable_types
    - only_throw_errors
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_constructors_over_static_methods
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_relative_imports
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last
    - sort_constructors_first
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_library_name
    - unnecessary_parenthesis
    - use_colored_box
    - use_decorated_box
    - use_key_in_widget_constructors
    - use_super_parameters
