targets:
  $default:
    builders:
      repository_generator:
        enabled: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"

builders:
  repository_generator:
    import: "package:dragonfly/builder.dart"
    builder_factories: [ "repositoryGenerator" ]
    build_extensions: { ".dart": [ ".repository.part" ] }
    auto_apply: dependents
    build_to: source